{
	"version": 1733521977,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/dapurwall.png",
		"images/blck.png",
		"images/furdp.png",
		"images/food.png",
		"images/furdp2.png",
		"images/gorm-sheet0.png",
		"images/exit-sheet0.png",
		"images/glow-sheet0.png",
		"images/loadgame-sheet0.png",
		"images/mainscreen-sheet0.png",
		"images/music-sheet0.png",
		"images/newgame-sheet0.png",
		"images/options-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/bed.png",
		"images/collider-sheet0.png",
		"images/light-sheet0.png",
		"images/nextscene-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/visionnight-sheet0.png",
		"images/zkey-sheet0.png",
		"images/doorsadney.png",
		"images/dialogborder-sheet0.png",
		"images/dialogdapur-sheet0.png",
		"images/goout-sheet0.png",
		"images/fadeout-sheet0.png",
		"images/bathinteract-sheet0.png",
		"images/ground.png",
		"images/sadneyhouse.png",
		"images/carss-sheet0.png",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/colup-sheet0.png",
		"images/dialog-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/download2-sheet0.png",
		"images/plg-sheet0.png",
		"media/door close.m4a",
		"media/door close.ogg",
		"media/door lock.m4a",
		"media/door lock.ogg",
		"media/door open.m4a",
		"media/door open.ogg",
		"media/sounds-of-button-selection-in-the-game-menu-sound-effect_ynsbl-cek1c_00_00_06_00_00_07_part (mp3cut.net).ogg",
		"media/sounds-of-button-selection-in-the-game-menu-sound-effect_ynsbl-cek1c_00_00_06_00_00_07_part (mp3cut.net).m4a",
		"media/talklong.m4a",
		"media/talklong.ogg",
		"media/talkmedium.m4a",
		"media/talkmedium.ogg",
		"media/talkmedium2.m4a",
		"media/talkmedium2.ogg",
		"media/talkshort.m4a",
		"media/talkshort.ogg",
		"media/talkverylong.m4a",
		"media/talkverylong.ogg",
		"media/bathroom sound effects (mp3cut.net).m4a",
		"media/bathroom sound effects (mp3cut.net).ogg",
		"media/picnic heal (full) omori sfx (mp3cut.net).m4a",
		"media/picnic heal (full) omori sfx (mp3cut.net).ogg",
		"media/omori ost - 014 acrophobia [extended].ogg",
		"media/omori ost - 014 acrophobia [extended].m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"ctev.webm"
	]
}